### PR TITLE
Fix missing humanize module

### PR DESCRIPTION
**Pull request by Sinled**
After updating to 0.3.0 version, grunt-tinypng starts to throw such error:

```
Loading "tinypng.js" tasks...ERROR
>> Error: Cannot find module 'humanize'
>>     at Function.Module._resolveFilename (module.js:338:15)
>>     at Function.Module._load (module.js:280:25)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
...
>> Error: Cannot find module 'humanize'
```

adding this module to `dependencies` should fix problem

### CODE REVIEW

**Comment by olegspetrovs319-eng** [comment]
Uploading VID-20251018-WA0012.mp4…

**Comment by olegspetrovs319-eng** [comment]
Olegspetrovs@gmail
